config/routes.rb
Rails.application.routes.draw do
  resources :volunteers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharityAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/volunteers/new.html.erb
<h1>build me bro!</h1>

<% if @volunteer.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@volunteer.errors.count, "error") %> prohibited
            this volunteer from being saved:</h2>
        <ul>
            <% @volunteer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<%= form_for :volunteer, url: volunteers_path do |f| %>

    <p>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </p>

    <p>
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name %>
    </p>

    <p>
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/volunteers/show.html.erb
<p>
    <%= @volunteer.appease %>
</p>
<p>
    <%= @volunteer.first_name %>
</p>
<p>
    <%= @volunteer.last_name %>
</p>